# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# the build will trigger on any changes to the master branch
trigger:
- master

# the build will run on a Microsoft hosted agent, using the lastest Windows VM Image
pool:
  vmImage: 'windows-latest'

# these variables are available throughout the build file
# just the build configuration is defined, in this case we are building Release packages
variables:
  buildConfiguration: 'Release'

jobs:
- job: Building
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Dotnet build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: 'Aark.Netatmo.SDK/Aark.Netatmo.SDK.csproj'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: 'BuildResult'
      publishLocation: 'pipeline'

- job: Testing
  dependsOn: Building
  condition: succeeded()
  steps:
    # Download the appsettings.json file stocked in the secure library of Azure DevOps.
    - task: DownloadSecureFile@1
      displayName: 'Get appsettings.json from secure file'
      name: AppSettings
      inputs:
        secureFile: 'appsettings.json'

    # Copy the appsettings.json file in the output directory.
    - task: CopyFiles@2
      displayName: 'Copy appsettings.json to the output directory'
      inputs: 
        sourceFolder: '$(Agent.TempDirectory)'
        contents: 'appsettings.json'
        targetFolder: '$(System.DefaultWorkingDirectory)\Aark.Netatmo.SDK.Test\bin\Debug\netcoreapp2.2\'

    - task: VSTest@2
      displayName: Execute tests
      continueOnError: true
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: **\Aark.Netatmo.SDK.Test.dll
        searchFolder: '$(System.DefaultWorkingDirectory)'
        codeCoverageEnabled: true

    # Run tests and collect of coverage.
    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'

- job: Packaging
  dependsOn: Testing
  condition: succeeded()
  steps:

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: 'Aark.Netatmo.SDK/Aark.Netatmo.SDK.csproj'
        feedsToUse: 'select'

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifact: 'BuildResult'
        targetPath: '$(Pipeline.Workspace)'

    - task: DotNetCoreCLI@2
      displayName: "Dotnet pack"
      inputs:
        command: 'pack'
        arguments: '--configuration $(buildConfiguration)'
        packagesToPack: 'Aark.Netatmo.SDK/Aark.Netatmo.SDK.csproj'
        nobuild: true
        versioningScheme: 'off'

    - task: NuGetCommand@2
      displayName: 'Nuget push'
      inputs:
        command: 'push'
        feedsToUse: 'select'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'Aarklendoia.Feed'
        versioningScheme: 'off'
        allowPackageConflicts: true